<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $colors = [
            ['name' => ['en' => 'Black', 'ar' => 'أسود'], 'value' => '#000000'],
            ['name' => ['en' => 'White', 'ar' => 'أبيض'], 'value' => '#FFFFFF'],
            ['name' => ['en' => 'Red', 'ar' => 'أحمر'], 'value' => '#FF0000'],
            ['name' => ['en' => 'Lime', 'ar' => 'ليموني'], 'value' => '#00FF00'],
            ['name' => ['en' => 'Blue', 'ar' => 'أزرق'], 'value' => '#0000FF'],
            ['name' => ['en' => 'Yellow', 'ar' => 'أصفر'], 'value' => '#FFFF00'],
            ['name' => ['en' => 'Cyan', 'ar' => 'سماوي'], 'value' => '#00FFFF'],
            ['name' => ['en' => 'Magenta', 'ar' => 'قرمزي'], 'value' => '#FF00FF'],
            ['name' => ['en' => 'Silver', 'ar' => 'فضي'], 'value' => '#C0C0C0'],
            ['name' => ['en' => 'Gray', 'ar' => 'رمادي'], 'value' => '#808080'],
            ['name' => ['en' => 'Maroon', 'ar' => 'بني داكن'], 'value' => '#800000'],
            ['name' => ['en' => 'Olive', 'ar' => 'زيتوني'], 'value' => '#808000'],
            ['name' => ['en' => 'Green', 'ar' => 'أخضر'], 'value' => '#008000'],
            ['name' => ['en' => 'Purple', 'ar' => 'بنفسجي'], 'value' => '#800080'],
            ['name' => ['en' => 'Teal', 'ar' => 'أزرق مخضر'], 'value' => '#008080'],
            ['name' => ['en' => 'Navy', 'ar' => 'أزرق داكن'], 'value' => '#000080'],
            ['name' => ['en' => 'AliceBlue', 'ar' => 'أزرق سماوي'], 'value' => '#F0F8FF'],
            ['name' => ['en' => 'AntiqueWhite', 'ar' => 'أبيض عتيق'], 'value' => '#FAEBD7'],
            ['name' => ['en' => 'Aqua', 'ar' => 'أزرق مائي'], 'value' => '#00FFFF'],
            ['name' => ['en' => 'Aquamarine', 'ar' => 'أزرق مائل للأخضر'], 'value' => '#7FFFD4'],
            ['name' => ['en' => 'Azure', 'ar' => 'أزرق سماوي'], 'value' => '#F0FFFF'],
            ['name' => ['en' => 'Beige', 'ar' => 'بيج'], 'value' => '#F5F5DC'],
            ['name' => ['en' => 'Bisque', 'ar' => 'بيج فاتح'], 'value' => '#FFE4C4'],
            ['name' => ['en' => 'BlanchedAlmond', 'ar' => 'لون اللوز المقشر'], 'value' => '#FFEBCD'],
            ['name' => ['en' => 'BlueViolet', 'ar' => 'أزرق بنفسجي'], 'value' => '#8A2BE2'],
            ['name' => ['en' => 'Brown', 'ar' => 'بني'], 'value' => '#A52A2A'],
            ['name' => ['en' => 'BurlyWood', 'ar' => 'بني داكن'], 'value' => '#DEB887'],
            ['name' => ['en' => 'CadetBlue', 'ar' => 'أزرق فاتح'], 'value' => '#5F9EA0'],
            ['name' => ['en' => 'Chartreuse', 'ar' => 'أخضر فاتح'], 'value' => '#7FFF00'],
            ['name' => ['en' => 'Chocolate', 'ar' => 'بني داكن'], 'value' => '#D2691E'],
            ['name' => ['en' => 'Coral', 'ar' => 'مرجاني'], 'value' => '#FF7F50'],
            ['name' => ['en' => 'CornflowerBlue', 'ar' => 'أزرق فاتح'], 'value' => '#6495ED'],
            ['name' => ['en' => 'Cornsilk', 'ar' => 'أصفر فاتح'], 'value' => '#FFF8DC'],
            ['name' => ['en' => 'Crimson', 'ar' => 'قرمزي داكن'], 'value' => '#DC143C'],
            ['name' => ['en' => 'DarkBlue', 'ar' => 'أزرق داكن'], 'value' => '#00008B'],
            ['name' => ['en' => 'DarkCyan', 'ar' => 'أزرق سماوي داكن'], 'value' => '#008B8B'],
            ['name' => ['en' => 'DarkGoldenrod', 'ar' => 'أصفر داكن'], 'value' => '#B8860B'],
            ['name' => ['en' => 'DarkGray', 'ar' => 'رمادي داكن'], 'value' => '#A9A9A9'],
            ['name' => ['en' => 'DarkGreen', 'ar' => 'أخضر داكن'], 'value' => '#006400'],
            ['name' => ['en' => 'DarkKhaki', 'ar' => 'كاكي داكن'], 'value' => '#BDB76B'],
            ['name' => ['en' => 'DarkMagenta', 'ar' => 'قرمزي داكن'], 'value' => '#8B008B'],
            ['name' => ['en' => 'DarkOliveGreen', 'ar' => 'أخضر زيتوني داكن'], 'value' => '#556B2F'],
            ['name' => ['en' => 'DarkOrange', 'ar' => 'برتقالي داكن'], 'value' => '#FF8C00'],
            ['name' => ['en' => 'DarkOrchid', 'ar' => 'أرجواني داكن'], 'value' => '#9932CC'],
            ['name' => ['en' => 'DarkRed', 'ar' => 'أحمر داكن'], 'value' => '#8B0000'],
            ['name' => ['en' => 'DarkSalmon', 'ar' => 'سمكي داكن'], 'value' => '#E9967A'],
            ['name' => ['en' => 'DarkSeaGreen', 'ar' => 'أخضر بحري داكن'], 'value' => '#8FBC8F'],
            ['name' => ['en' => 'DarkSlateBlue', 'ar' => 'أزرق داكن'], 'value' => '#483D8B'],
            ['name' => ['en' => 'DarkSlateGray', 'ar' => 'رمادي داكن'], 'value' => '#2F4F4F'],
            ['name' => ['en' => 'DarkTurquoise', 'ar' => 'أزرق تركواز داكن'], 'value' => '#00CED1'],
            ['name' => ['en' => 'DarkViolet', 'ar' => 'أرجواني داكن'], 'value' => '#9400D3'],
            ['name' => ['en' => 'DeepPink', 'ar' => 'وردي داكن'], 'value' => '#FF1493'],
            ['name' => ['en' => 'DeepSkyBlue', 'ar' => 'أزرق سماوي داكن'], 'value' => '#00BFFF'],
            ['name' => ['en' => 'DimGray', 'ar' => 'رمادي داكن'], 'value' => '#696969'],
            ['name' => ['en' => 'DodgerBlue', 'ar' => 'أزرق فاتح'], 'value' => '#1E90FF'],
            ['name' => ['en' => 'FireBrick', 'ar' => 'لون الطوب الحمراء'], 'value' => '#B22222'],
            ['name' => ['en' => 'FloralWhite', 'ar' => 'أبيض زهري'], 'value' => '#FFFAF0'],
            ['name' => ['en' => 'ForestGreen', 'ar' => 'أخضر غامق'], 'value' => '#228B22'],
            ['name' => ['en' => 'Fuchsia', 'ar' => 'فوشيا'], 'value' => '#FF00FF'],
            ['name' => ['en' => 'Gainsboro', 'ar' => 'رمادي فاتح'], 'value' => '#DCDCDC'],
            ['name' => ['en' => 'GhostWhite', 'ar' => 'أبيض زهري'], 'value' => '#F8F8FF'],
            ['name' => ['en' => 'Gold', 'ar' => 'ذهبي'], 'value' => '#FFD700'],
            ['name' => ['en' => 'Goldenrod', 'ar' => 'أصفر داكن'], 'value' => '#DAA520'],
            ['name' => ['en' => 'GreenYellow', 'ar' => 'أخضر فاتح'], 'value' => '#ADFF2F'],
            ['name' => ['en' => 'Honeydew', 'ar' => 'أخضر فاتح'], 'value' => '#F0FFF0'],
            ['name' => ['en' => 'HotPink', 'ar' => 'وردي فاتح'], 'value' => '#FF69B4'],
            ['name' => ['en' => 'IndianRed', 'ar' => 'أحمر هندي'], 'value' => '#CD5C5C'],
            ['name' => ['en' => 'Indigo', 'ar' => 'نيلي داكن'], 'value' => '#4B0082'],
            ['name' => ['en' => 'Ivory', 'ar' => 'عاجي'], 'value' => '#FFFFF0'],
            ['name' => ['en' => 'Khaki', 'ar' => 'كاكي'], 'value' => '#F0E68C'],
            ['name' => ['en' => 'Lavender', 'ar' => 'لافندر'], 'value' => '#E6E6FA'],
            ['name' => ['en' => 'LavenderBlush', 'ar' => 'لافندر'], 'value' => '#FFF0F5'],
            ['name' => ['en' => 'LawnGreen', 'ar' => 'أخضر فاتح'], 'value' => '#7CFC00'],
            ['name' => ['en' => 'LemonChiffon', 'ar' => 'ليموني فاتح'], 'value' => '#FFFACD'],
            ['name' => ['en' => 'LightBlue', 'ar' => 'أزرق فاتح'], 'value' => '#ADD8E6'],
            ['name' => ['en' => 'LightCoral', 'ar' => 'مرجاني فاتح'], 'value' => '#F08080'],
            ['name' => ['en' => 'LightCyan', 'ar' => 'أزرق سماوي فاتح'], 'value' => '#E0FFFF'],
            ['name' => ['en' => 'LightGoldenrodYellow', 'ar' => 'أصفر فاتح'], 'value' => '#FAFAD2'],
            ['name' => ['en' => 'LightGray', 'ar' => 'رمادي فاتح'], 'value' => '#D3D3D3'],
            ['name' => ['en' => 'LightGreen', 'ar' => 'أخضر فاتح'], 'value' => '#90EE90'],
            ['name' => ['en' => 'LightPink', 'ar' => 'وردي فاتح'], 'value' => '#FFB6C1'],
            ['name' => ['en' => 'LightSalmon', 'ar' => 'سمكي فاتح'], 'value' => '#FFA07A'],
            ['name' => ['en' => 'LightSeaGreen', 'ar' => 'أخضر بحري فاتح'], 'value' => '#20B2AA'],
            ['name' => ['en' => 'LightSkyBlue', 'ar' => 'أزرق سماوي فاتح'], 'value' => '#87CEFA'],
            ['name' => ['en' => 'LightSlateGray', 'ar' => 'رمادي فاتح'], 'value' => '#778899'],
            ['name' => ['en' => 'LightSteelBlue', 'ar' => 'أزرق فاتح'], 'value' => '#B0C4DE'],
            ['name' => ['en' => 'LightYellow', 'ar' => 'أصفر فاتح'], 'value' => '#FFFFE0'],
            ['name' => ['en' => 'LimeGreen', 'ar' => 'أخضر ليموني'], 'value' => '#32CD32'],
            ['name' => ['en' => 'Linen', 'ar' => 'ليني'], 'value' => '#FAF0E6'],
            ['name' => ['en' => 'Magenta', 'ar' => 'قرمزي'], 'value' => '#FF00FF'],
            ['name' => ['en' => 'MediumAquamarine', 'ar' => 'أزرق مائل للأخضر'], 'value' => '#66CDAA'],
            ['name' => ['en' => 'MediumBlue', 'ar' => 'أزرق'], 'value' => '#0000CD'],
            ['name' => ['en' => 'MediumOrchid', 'ar' => 'أرجواني']],
            ['name' => ['en' => 'MediumPurple', 'ar' => 'أرجواني فاتح'], 'value' => '#9370DB'],
            ['name' => ['en' => 'MediumSeaGreen', 'ar' => 'أخضر بحري'], 'value' => '#3CB371'],
            ['name' => ['en' => 'MediumSlateBlue', 'ar' => 'أزرق أرجواني'], 'value' => '#7B68EE'],
            ['name' => ['en' => 'MediumSpringGreen', 'ar' => 'أخضر فاتح'], 'value' => '#00FA9A'],
            ['name' => ['en' => 'MediumTurquoise', 'ar' => 'تركواز'], 'value' => '#48D1CC'],
            ['name' => ['en' => 'MediumVioletRed', 'ar' => 'أحمر فاتح'], 'value' => '#C71585'],
            ['name' => ['en' => 'MidnightBlue', 'ar' => 'أزرق منتصف الليل'], 'value' => '#191970'],
            ['name' => ['en' => 'MintCream', 'ar' => 'أبيض مائل للأخضر الفاتح'], 'value' => '#F5FFFA'],
            ['name' => ['en' => 'MistyRose', 'ar' => 'وردي فاتح'], 'value' => '#FFE4E1'],
            ['name' => ['en' => 'Moccasin', 'ar' => 'بني فاتح'], 'value' => '#FFE4B5'],
            ['name' => ['en' => 'NavajoWhite', 'ar' => 'أبيض فاتح'], 'value' => '#FFDEAD'],
            ['name' => ['en' => 'Navy', 'ar' => 'أزرق داكن'], 'value' => '#000080'],
            ['name' => ['en' => 'OldLace', 'ar' => 'بيج فاتح'], 'value' => '#FDF5E6'],
            ['name' => ['en' => 'Olive', 'ar' => 'زيتوني'], 'value' => '#808000'],
            ['name' => ['en' => 'OliveDrab', 'ar' => 'أخضر زيتوني'], 'value' => '#6B8E23'],
            ['name' => ['en' => 'Orange', 'ar' => 'برتقالي'], 'value' => '#FFA500'],
            ['name' => ['en' => 'OrangeRed', 'ar' => 'أحمر برتقالي'], 'value' => '#FF4500'],
            ['name' => ['en' => 'Orchid', 'ar' => 'أرجواني'], 'value' => '#DA70D6'],
            ['name' => ['en' => 'PaleGoldenrod', 'ar' => 'أصفر فاتح'], 'value' => '#EEE8AA'],
            ['name' => ['en' => 'PaleGreen', 'ar' => 'أخضر فاتح'], 'value' => '#98FB98'],
            ['name' => ['en' => 'PaleTurquoise', 'ar' => 'تركواز فاتح'], 'value' => '#AFEEEE'],
            ['name' => ['en' => 'PaleVioletRed', 'ar' => 'أحمر أرجواني'], 'value' => '#DB7093'],
            ['name' => ['en' => 'PapayaWhip', 'ar' => 'أبيض مائل للأصفر'], 'value' => '#FFEFD5'],
            ['name' => ['en' => 'PeachPuff', 'ar' => 'أصفر فاتح'], 'value' => '#FFDAB9'],
            ['name' => ['en' => 'Peru', 'ar' => 'بني'], 'value' => '#CD853F'],
            ['name' => ['en' => 'Pink', 'ar' => 'وردي'], 'value' => '#FFC0CB'],
            ['name' => ['en' => 'Plum', 'ar' => 'أرجواني فاتح'], 'value' => '#DDA0DD'],
            ['name' => ['en' => 'PowderBlue', 'ar' => 'أزرق فاتح'], 'value' => '#B0E0E6'],
            ['name' => ['en' => 'Purple', 'ar' => 'بنفسجي'], 'value' => '#800080'],
            ['name' => ['en' => 'Red', 'ar' => 'أحمر'], 'value' => '#FF0000'],
            ['name' => ['en' => 'RosyBrown', 'ar' => 'بني وردي'], 'value' => '#BC8F8F'],
            ['name' => ['en' => 'RoyalBlue', 'ar' => 'أزرق فاتح'], 'value' => '#4169E1'],
            ['name' => ['en' => 'SaddleBrown', 'ar' => 'بني داكن'], 'value' => '#8B4513'],
            ['name' => ['en' => 'Salmon', 'ar' => 'سمكي'], 'value' => '#FA8072'],
            ['name' => ['en' => 'SandyBrown', 'ar' => 'بني فاتح'], 'value' => '#F4A460'],
            ['name' => ['en' => 'SeaGreen', 'ar' => 'أخضر بحري'], 'value' => '#2E8B57'],
            ['name' => ['en' => 'Seashell', 'ar' => 'أبيض فاتح'], 'value' => '#FFF5EE'],
            ['name' => ['en' => 'Sienna', 'ar' => 'برتقالي داكن'], 'value' => '#A0522D'],
            ['name' => ['en' => 'Silver', 'ar' => 'فضي'], 'value' => '#C0C0C0'],
            ['name' => ['en' => 'SkyBlue', 'ar' => 'أزرق سماوي'], 'value' => '#87CEEB'],
            ['name' => ['en' => 'SlateBlue', 'ar' => 'أزرق'], 'value' => '#6A5ACD'],
            ['name' => ['en' => 'SlateGray', 'ar' => 'رمادي'], 'value' => '#708090'],
            ['name' => ['en' => 'Snow', 'ar' => 'أبيض ثلجي'], 'value' => '#FFFAFA'],
            ['name' => ['en' => 'SpringGreen', 'ar' => 'أخضر فاتح'], 'value' => '#00FF7F'],
            ['name' => ['en' => 'SteelBlue', 'ar' => 'أزرق فاتح'], 'value' => '#4682B4'],
            ['name' => ['en' => 'Tan', 'ar' => 'بني'], 'value' => '#D2B48C'],
            ['name' => ['en' => 'Teal', 'ar' => 'أزرق مخضر'], 'value' => '#008080'],
            ['name' => ['en' => 'Thistle', 'ar' => 'بنفسجي فاتح'], 'value' => '#D8BFD8'],
            ['name' => ['en' => 'Tomato', 'ar' => 'أحمر فاتح'], 'value' => '#FF6347'],
            ['name' => ['en' => 'Turquoise', 'ar' => 'تركواز'], 'value' => '#40E0D0'],
            ['name' => ['en' => 'Violet', 'ar' => 'بنفسجي'], 'value' => '#EE82EE'],
            ['name' => ['en' => 'Wheat', 'ar' => 'أصفر فاتح'], 'value' => '#F5DEB3'],
            ['name' => ['en' => 'White', 'ar' => 'أبيض'], 'value' => '#FFFFFF'],
            ['name' => ['en' => 'WhiteSmoke', 'ar' => 'أبيض مدخن'], 'value' => '#F5F5F5'],
            ['name' => ['en' => 'Yellow', 'ar' => 'أصفر'], 'value' => '#FFFF00'],
            ['name' => ['en' => 'YellowGreen', 'ar' => 'أخضر فاتح'], 'value' => '#9ACD32']
        ];

        foreach ($colors as $color) {
            // Seed colors table
            $colorId = DB::table('colors')->insertGetId(['value' => $color['value']]);

            // Seed colors_translations table
            DB::table('colors_translations')->insert([
                'color_id' => $colorId,
                'locale' => 'en',
                'name' => $color['name']['en'],
            ]);

            DB::table('colors_translations')->insert([
                'color_id' => $colorId,
                'locale' => 'ar',
                'name' => $color['name']['ar'],
            ]);
        }

    }
}
